version: "3.8"

services:
    web:
        container_name: web
        image: nginx:${DOCKER_NGINX_VERSION:-1.24}-alpine
        # These variables are passed into the container.
        environment:
            TZ: ${DOCKER_TZ:-Europe/Paris}
            UID: ${HOST_UID:-1000}
            GID: ${HOST_GID:-1000}
        volumes:
            - ./files/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./files/nginx/conf.d/file-upload.conf:/etc/nginx/conf.d/file-upload.conf
            - ./files/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./files/nginx/conf.d/sites-enabled.conf:/etc/nginx/conf.d/sites-enabled.conf
            - ./files/nginx/html:/var/www/html
            - ./files/nginx/ssl:/etc/nginx/ssl
            - ./logs/nginx:/var/log/nginx
            - ${NGINX_APP:-./app}:/var/www/app
        ports:
            - ${DOCKER_NGINX_PORT:-80}:80
            - ${DOCKER_NGINX_SSL_PORT:-443}:443
        depends_on:
            - php
            - database
        networks:
            - backend

    php:
        container_name: php
        build:
            context: .
            dockerfile: files/php/Dockerfile
            target: fpm
            # These variables are passed to Dockerfile.
            args:
                PHP_VERSION: ${DOCKER_PHP_VERSION:-8.2}
                UID: ${HOST_UID:-1000}
                GID: ${HOST_GID:-1000}
        # Run with user priviliges by default.
        user: "${HOST_UID:-1000}:${HOST_GID-1000}"
        # These variables are passed into the container.
        environment:
            TZ: ${DOCKER_TZ:-Europe/Paris}
            UID: ${HOST_UID:-1000}
            GID: ${HOST_GID:-1000}
        volumes:
            - ${NGINX_APP:-./app}:/var/www/app
            - ./logs/php:/var/log/php
            - ./files/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
            - ./files/php/conf.d/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
        working_dir: /var/www/app
        depends_on:
            - database
        networks:
            - backend

    database:
        container_name: database
        image: mariadb:${DOCKER_MARIADB_VERSION:-10.11}
        # Run with user priviliges by default.
        # user: ${HOST_USER:-www-data}
        # These variables are passed into the container.
        environment:
            MYSQL_ROOT_PASSWORD: ${DOCKER_MARIADB_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${DOCKER_MARIADB_DATABASE:-app}
            MYSQL_USER: ${DOCKER_MARIADB_USER:-app}
            MYSQL_PASSWORD: ${DOCKER_MARIADB_PASSWORD:-app}
            TZ: ${DOCKER_TZ:-Europe/Paris}
            UID: ${HOST_UID:-1000}
            GID: ${HOST_GID:-1000}
        volumes:
            - ./data/mariadb:/var/lib/mysql
            - ./logs/mariadb:/var/log/mysql
        ports:
            - ${DOCKER_MARIADB_PORT:-3306}:3306
        networks:
            - backend

    composer:
        container_name: composer
        # Run with user priviliges by default.
        user: "${HOST_UID:-1000}:${HOST_GID-1000}"
        build:
            context: .
            dockerfile: files/php/Dockerfile
            target: composer
            # These variables are passed to Dockerfile.
            args:
                PHP_VERSION: ${DOCKER_PHP_VERSION:-8.2}
                UID: ${HOST_UID:-1000}
                GID: ${HOST_GID:-1000}
        # These variables are passed into the container.
        environment:
            TZ: ${DOCKER_TZ:-Europe/Paris}
            UID: ${HOST_UID:-1000}
            GID: ${HOST_GID:-1000}
        volumes:
            - ${NGINX_APP:-./app}:/var/www/app
            - ./logs/composer:/var/log/php
            - ./files/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
            - ./files/php/conf.d/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
        working_dir: /var/www/app

    node:
        container_name: node
        # Run with user priviliges by default.
        user: "${HOST_UID:-1000}:${HOST_GID-1000}"
        image: node:${DOCKER_NODE_VERSION:-16}-alpine
        # These variables are passed into the container.
        environment:
            TZ: ${DOCKER_TZ:-Europe/Paris}
            UID: ${HOST_UID:-1000}
            GID: ${HOST_GID:-1000}
        volumes:
            - ${NGINX_APP:-./app}:/var/www/app
        working_dir: /var/www/app

    mailer:
        container_name: mailer
        # Run with user priviliges by default.
        #user: ${HOST_USER:-www-data}
        image: schickling/mailcatcher
        # These variables are passed into the container.
        environment:
            TZ: ${DOCKER_TZ:-Europe/Paris}
        ports:
            - 1025:1025
            - 1080:1080
        networks:
            - backend

    whoami-one:
        image: containous/whoami
        environment:
            - VIRTUAL_HOST=${DOCKER_NGINX_URL:-app.dev.localhost}

networks:
    backend:
        driver: bridge
